
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
        - id: check-yaml
        - id: end-of-file-fixer
        - id: trailing-whitespace
        - id: check-merge-conflict

    - repo: https://github.com/pre-commit/mirrors-clang-format
      rev: v15.0.6
      hooks:
        - id: clang-format
          name: Formating C files with Clang-Format
          files: ^app/.*\.(c|cc|cpp|cxx|h|hpp)$

    - repo: local
      hooks:
        - id: memory-check
          name: Memory check (Flash/RAM)
          entry: bash
          args:
            - -lc
            - |
              set -euo pipefail
              make -j
              tools/check_memory.sh build/vizcacha-stm32f4.elf
          language: system
          pass_filenames: false
          stages: [pre-commit, pre-push]
          verbose: true
